### ISSUE TITLE
Connection issue with the latest version of the RFXtrx433e firmware

### ISSUE THREAD

**Issue by experida** [fritz-smh/domogik-plugin-rfxcom#16]
2017-01-03 23:18:45,675 domogik-rfxcom INFO The client is configured. Continuing (hoping that the user applied the appropriate configuration ;)
2017-01-03 23:18:45,675 domogik-rfxcom INFO Retrieve the devices list for this client...
2017-01-03 23:18:45,696 domogik-rfxcom WARNING There is no device created for this client
2017-01-03 23:18:45,697 domogik-rfxcom INFO Request query config for client rfxcom : key rfxcom_device
2017-01-03 23:18:45,718 domogik-rfxcom DEBUG Query config : successfull response : <MQMessage(action=config.result, data='{u'status': True, u'name': u'rfxcom', u'reason': u'', u'value': u'/dev/ttyUSB0', u'host': u'yana', u'key': u'rfxco$
2017-01-03 23:18:45,719 domogik-rfxcom INFO Value for 'rfxcom_device' is : /dev/ttyUSB0
2017-01-03 23:18:45,720 domogik-rfxcom INFO Casting value for key 'rfxcom_device' in type 'string'...
2017-01-03 23:18:45,720 domogik-rfxcom INFO Value is : /dev/ttyUSB0
2017-01-03 23:18:45,722 domogik-rfxcom INFO Try to register a thread twice: <Thread(thread-monitor, started 1941959776)>
2017-01-03 23:18:45,722 domogik-rfxcom INFO Start the write_rfx thread
2017-01-03 23:18:45,723 domogik-rfxcom DEBUG New listener 97a3b976-d202-11e6-a9ed-b827eb7eb251, filter : {'xpltype': 'xpl-cmnd', 'schema': 'ac.basic'}
2017-01-03 23:18:45,724 domogik-rfxcom INFO **** Open RFXCOM ****
2017-01-03 23:18:45,725 domogik-rfxcom INFO Try to open RFXCOM : /dev/ttyUSB0
2017-01-03 23:18:45,727 domogik-rfxcom INFO RFXCOM opened
2017-01-03 23:18:45,728 domogik-rfxcom INFO **** Set up the RFXCOM ****
2017-01-03 23:18:45,728 domogik-rfxcom INFO Send 'reset' message : 0D00000000000000000000000000
2017-01-03 23:18:45,729 domogik-rfxcom INFO Wait 2 seconds...
2017-01-03 23:18:47,731 domogik-rfxcom INFO Flush the serial port
2017-01-03 23:18:47,732 domogik-rfxcom INFO Send 'get status' message : 0D00000102000000000000000000
2017-01-03 23:18:47,733 domogik-rfxcom INFO Wait for the status message...
2017-01-03 23:18:47,733 domogik-rfxcom INFO Start listening to the rfxcom device for lenght=13, type=01
2017-01-03 23:18:47,734 domogik-rfxcom DEBUG Waiting for a packet from the rfxcom with a length of 13 and hoping type will be 01...
2017-01-03 23:18:47,738 domogik-rfxcom DEBUG Packet of length 20 (0x14) received, start processing...
2017-01-03 23:18:47,738 domogik-rfxcom DEBUG This is not the message we are waiting for
2017-01-03 23:18:47,739 domogik-rfxcom DEBUG Waiting for a packet from the rfxcom with a length of 13 and hoping type will be 01...
2017-01-03 23:18:47,743 domogik-rfxcom ERROR Error while opening RFXCOM : /dev/ttyUSB0. Check if it is the good device or if you have the good permissions on it. Error : Traceback (most recent call last):
  File "/var/lib/domogik/domogik_packages/plugin_rfxcom/lib/rfxcom.py", line 205, in open
    status_msg = self.wait_for(self.stop, 13, "01")
  File "/var/lib/domogik/domogik_packages/plugin_rfxcom/lib/rfxcom.py", line 342, in wait_for
    data_len = self.rfxcom.read()

**Comment by jgaret** [comment]
I think this issue can be closed, the problem with the first packet length has been corrected by commit https://github.com/fritz-smh/domogik-plugin-rfxcom/commit/b2a23d9926bd0c48b72021bf69f65ddf3c5d4201 on branch develop.
